### ISSUE TITLE
should `hydrate` coerce `None` to an empty dictionary or list?

### ISSUE THREAD

**Issue by mishaschwartz** [developmentseed/hydraters#7]
The tests for `pypgstac` make it seem like the `hydrate` function is expected to be able to treat a None value as if it were an empty dictionary:

```py
    def test_base_none(self) -> None:
        base_item = {"value": None}
        dehydrated = {"value": {"a": "b"}}
        hydrated = self.hydrate(base_item, dehydrated)
        assert hydrated == {"value": {"a": "b"}}
```

See the relevant code here: `https://github.com/stac-utils/pgstac/blob/6c569c0ee56bd9519ad947cbcaa8bfbcfade15bb/src/pypgstac/tests/hydration/test_hydrate.py#L241-L245

Right now, the `hydrate` function does not do that. Instead it tries to downcast the `None` value to a dict and raises an error since it can't do that:

https://github.com/developmentseed/hydraters/blob/d3946d3a7fa6674698f1a88af43511b561cb4f07/src/lib.rs#L42-L49

Do we want to change the code here so that if `item` or `base` is None, we convert it to a dict or list? Or if not, we should update the tests in [pgstac](https://github.com/stac-utils/pgstac).

What do you think?

**Comment by gadomski** [comment]
Yup, I'll update — I must have pulled the test suite from somewhere else so I didn't get https://github.com/stac-utils/pgstac/pull/263. Thanks for the catch.
